#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WAVE2_ROOT="${REPO_ROOT}/wave2_network"
ICL_DIR="${WAVE2_ROOT}/packages/icl"
NODE_DIR="${WAVE2_ROOT}/packages/node-reineira"
FRONTEND_DIR="${WAVE2_ROOT}/packages/frontend"

DEFAULT_BLINDFERENCE_INPUT_VAULT_ADDRESS="0x8dD7B2A9B69C76A69d33B2DF46426Cbe657a902b"
DEFAULT_BLINDFERENCE_AGENT_ADDRESS="0xc9208B8aCAaD3abFc955a575719BB8F21640A6fE"
DEFAULT_BLINDFERENCE_ATTESTOR_ADDRESS="0x74454F689F28EfbEF6Ef9F3F14e56ac62CA8EC49"
DEFAULT_BLINDFERENCE_UNDERWRITER_ADDRESS="0xcbbdcb1b42DE4Ed52f7ceD752c65652EE317B601"
DEFAULT_MOCK_ORACLE_ADDRESS="0xDe9AE4b048bF320Db6492e2AfD0516392EBA05Fc"

load_icl_env() {
  if [[ ! -f "${ICL_DIR}/.env" ]]; then
    echo "Missing ${ICL_DIR}/.env" >&2
    exit 1
  fi

  set -a
  # shellcheck source=/dev/null
  source "${ICL_DIR}/.env"
  set +a

  export BLINDFERENCE_AGENT_ADDRESS="${BLINDFERENCE_AGENT_ADDRESS:-$DEFAULT_BLINDFERENCE_AGENT_ADDRESS}"
  export BLINDFERENCE_ATTESTOR_ADDRESS="${BLINDFERENCE_ATTESTOR_ADDRESS:-$DEFAULT_BLINDFERENCE_ATTESTOR_ADDRESS}"
  export BLINDFERENCE_UNDERWRITER_ADDRESS="${BLINDFERENCE_UNDERWRITER_ADDRESS:-$DEFAULT_BLINDFERENCE_UNDERWRITER_ADDRESS}"
  export MOCK_ORACLE_ADDRESS="${MOCK_ORACLE_ADDRESS:-$DEFAULT_MOCK_ORACLE_ADDRESS}"
}

resolve_operator_keys() {
  if [[ -n "${DEMO_OPERATOR_PRIVATE_KEY1:-}" && -n "${DEMO_OPERATOR_PRIVATE_KEY2:-}" && -n "${DEMO_OPERATOR_PRIVATE_KEY3:-}" ]]; then
    export DEMO_OPERATOR_PRIVATE_KEY1 DEMO_OPERATOR_PRIVATE_KEY2 DEMO_OPERATOR_PRIVATE_KEY3
    return
  fi

  if [[ -z "${DEMO_OPERATOR_PRIVATE_KEYS:-}" ]]; then
    echo "Missing DEMO_OPERATOR_PRIVATE_KEYS or numbered DEMO_OPERATOR_PRIVATE_KEY1/2/3 in ${ICL_DIR}/.env" >&2
    exit 1
  fi

  IFS=',' read -r DEMO_OPERATOR_PRIVATE_KEY1 DEMO_OPERATOR_PRIVATE_KEY2 DEMO_OPERATOR_PRIVATE_KEY3 <<< "${DEMO_OPERATOR_PRIVATE_KEYS}"
  export DEMO_OPERATOR_PRIVATE_KEY1 DEMO_OPERATOR_PRIVATE_KEY2 DEMO_OPERATOR_PRIVATE_KEY3
}

resolve_gemini_api_key() {
  if [[ -n "${GOOGLE_API_KEY:-}" ]]; then
    printf '%s' "${GOOGLE_API_KEY}"
    return
  fi
  printf '%s' "${GEMINI_API_KEY:-}"
}
